callnumber_to_barcode/urls.py
"""
URLs for the deduplication app.
"""

from django.urls import path
from . import views

app_name = "callnumber_to_barcode"

urlpatterns = [
    # Start page with list of collections to dedup, this view is not protected by login
    path("", views.index, name="index"),
    path("<slug:col_name>", views.collection, name="collection"),
    path("<slug:col_name>/update/<str:item_id>", views.update, name="update"),
    # Views to manage login and logout. The login view does not require
    # authentication to be accessed
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view")
]

dedup/urls.py
"""
URLs for the deduplication app.
"""

from django.urls import path
from . import views

app_name = "dedup"

urlpatterns = [
    # Start page with list of collections to dedup, this view is not protected by login
    path("", views.index, name="index"),

    # Collection page with list of records to dedup, main dedup view
    path("col/<slug:col_name>", views.collection, name="collection"),

    # Collection page with list of records to dedup, main dedup view
    path("col/<slug:col_name>/export", views.get_matching_records, name="get_matching_records"),

    # API used by the frontend to get the records to dedup
    path("col/<slug:col_name>/locrecids", views.get_local_record_ids, name="get_local_record_ids"),

    # API used by the frontend to get the data of the local record to dedup
    path("col/<slug:col_name>/locrec/<str:rec_id>", views.local_rec, name="local_rec"),

    # API used by the frontend to save dedup results int the training data
    path("training/add", views.add_to_training_data, name="add_to_training_data"),

    # Views to manage login and logout. The login view does not require
    # authentication to be accessed
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view")

    # path("dnbrec/<str:rec_id>", views.get_dnb_rec, name="get_dnb_rec"),
]

slsptools/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('dedup/', include('dedup.urls')),
    path('callnumber_to_barcode/', include('callnumber_to_barcode.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),

    # Views to manage login and logout. The login view does not require
    # authentication to be accessed
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view"),
    # path("api_threshold/", views.api_threshold_probe, name="api_threshold_probe"),
]

callnumber_to_barcode/views.py
# Django imports
import http

from django.http import HttpResponse, JsonResponse, HttpRequest
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse
from almapiwrapper import ApiKeys
from almapiwrapper.inventory import Item

from django.http import HttpResponse
import pymongo
import os
import re
from lxml import etree

# Get the uri to connect to the MongoDB databases, it has all the required
# rights to use the following databases: records, dedup
mongo_uri = os.getenv('mongodb_dedup_uri')
mongo_client = pymongo.MongoClient(mongo_uri)

# As the collection is related the material type, we define globally only the database
# for each material type
mongo_db_callnumbers = mongo_client[os.getenv('callnumbers_db')]

def index(request: HttpRequest) -> HttpResponse:
    """
    Display the list of collections available in the dedup database

    This view is unprotected and can be accessed by anyone. It displays the
    list of collections. The application is able to dedup several collections
    without any hard coding. We display all collections of `dedup_db` except
    the ones starting with 'NZ_' and the training data collection.
    """
    # Fetch collections names from the database
    cols = [col for col in mongo_db_callnumbers.list_collection_names()
            if is_col_allowed(col, request) is True]

    # Render the template with the list of collections
    return render(request, 'callnumber_to_barcode/index.html', {"cols": cols})


def collection(request, col_name):

    # We check that the collection name provided in url exists
    if col_name not in mongo_db_callnumbers.list_collection_names():
        return HttpResponse(f'Collection "{col_name}" not found', status=404)
    col = mongo_db_callnumbers[col_name]

    callnumber_query = request.GET.get('callnumber', '')

    recs_1 = list(col.find({'callnumber': callnumber_query}))

    recs_2 = list(col.find({
        'callnumber': {
            '$regex': f'^{callnumber_query}',
        '$options': 'i'
    }
    }).limit(500))
    itemids = [rec['item_id'] for rec in recs_1]
    recs_2 = natural_sort([rec for rec in recs_2 if rec['item_id'] not in itemids])
    recs = recs_1 + recs_2
    recs = recs[:500]

    return render(request,
                  'callnumber_to_barcode/collection.html',
                  {'recs': recs, 'col_name': col_name})

def update(request, item_id=None, col_name=None):
    # We check that the collection name provided in url exists
    if col_name not in mongo_db_callnumbers.list_collection_names():
        return HttpResponse(f'Collection "{col_name}" not found', status=404)
    col = mongo_db_callnumbers[col_name]
    callnumber = request.GET.get('callnumber', '')
    new_barcode = request.POST.get('new_barcode', None)
    if new_barcode == '':
        new_barcode = None
    col.update_one({'item_id': item_id}, {'$set': {'new_barcode': new_barcode, 'error': False}})
    rec = col.find_one({'item_id': item_id})
    if rec is None:
        return redirect(f"{reverse('callnumber_to_barcode:collection', kwargs={'col_name': col_name})}?callnumber={callnumber}")
    zone = col_name.split('_')[0]
    item = Item(rec['mms_id'], rec['holding_id'], rec['item_id'], zone=zone, env='P')
    if item.error is True:
        col.update_one({'item_id': item_id}, {'$set': {'new_barcode': None, 'error': True}})
        return redirect(f"{reverse('callnumber_to_barcode:collection', kwargs={'col_name': col_name})}?callnumber={callnumber}")

    # We use the old barcode if the new one is empty, we add error flag
    if new_barcode is not None:
        item.data.find('item_data/barcode').text = new_barcode
    else:
        item.data.find('item_data/barcode').text = rec['barcode']
        col.update_one({'item_id': item_id}, {'$set': {'new_barcode': None, 'error': True}})
    item.update()
    if item.error is True:
        col.update_one({'item_id': item_id}, {'$set': {'new_barcode': None, 'error': True}})

    return redirect(f"{reverse('callnumber_to_barcode:collection', kwargs={'col_name': col_name})}?callnumber={callnumber}")


def login_view(request):
    """Manage login of the user

    It uses the AuthenticationForm to authenticate the user.
    If the user is authenticated, it will redirect to the index page.
    """
    # We check the method of the request, post is used to send the form
    # and get is used to display the form
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        # We collect the data from the form and check if it's valid
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            # Redirection to the index page if the user is authenticated
            if user is not None:
                login(request, user)
                return redirect('callnumber_to_barcode:index')

    return render(request, 'callnumber_to_barcode/login.html', {'form': AuthenticationForm()})


def logout_view(request):
    """Logout the user and redirect to the index page"""
    logout(request)
    return redirect('callnumber_to_barcode:index')


def is_col_allowed(col_name: str, request: HttpRequest) -> bool:
    """Check if the user has access to the collection
    This function checks if the user has access to the collection

    Parameters:
    -----------
    col_name : str
        The name of the collection to check.
    request : HttpRequest
        The request object containing user information.

    Returns:
    --------
    bool
        True if the user has access to the collection, False otherwise.
    """

    # At least one group must be associated to the collection
    user_groups = list(request.user.groups.values_list("name", flat=True))
    if any(col_name.startswith(user_group) for user_group in user_groups):
        return True
    return False


def natural_sort(items):
    def natural_key(item):

        text = item['callnumber']
        # Split the string into parts: digits are converted to integers, others stay as strings
        return [int(part) if part.isdigit() else part for part in re.split(r'(\d+)', text)]

    return sorted(items, key=natural_key)

callnumber_to_barcode/templates/callnumber_to_barcode/collection.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>SLSP tool: callnumber => barcode ({{ col_name }})</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'callnumber_to_barcode/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}">
    <script src="https://unpkg.com/vue@3.2.29/dist/vue.global.js"></script>
</head>
<body>
<div class="container-fluid">
    <header>
        <div class="row mb-2">
            <div class="col-10">
                <h1>SLSP tool: callnumber => barcode  <span class="text-muted fs-5 ms-2">({{ col_name }})</span></h1>
            </div>
            <div class="col-2 text-end">
                {% if user.is_authenticated %}
                <a href="{% url 'callnumber_to_barcode:logout_view' %}">Logout</a>
                {% else %}
                <a href="{% url 'callnumber_to_barcode:login_view' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
    {% if user.is_authenticated %}
<div class="container">

<form method="get" action="{% url 'callnumber_to_barcode:collection' col_name=col_name %}" class="d-flex align-items-center mb-4">
  <label for="callnumberSearch" class="form-label me-2 mb-0">Callnumber</label>
  <input type="text" class="form-control me-2" id="callnumberSearch" name="callnumber" placeholder="Search by Callnumber" value="{{ request.GET.callnumber }}" style="max-width: 200px;">
  <button type="submit" class="btn btn-primary">Search</button>
</form>


</div>
<div class="container">
  <div class="row fw-bold border-bottom pb-2 mb-2">
    <div class="col-lg-2 col-md-2 col-sm-12">Callnumber</div>
    <div class="col-lg-2 col-md-4 col-sm-12">MMS ID</div>
    <div class="col-lg-5 col-md-8 col-sm-12">Title</div>
    <div class="col-lg-2 col-md-3 col-sm-12">New barcode</div>
    <div class="col-lg-1 col-md-1 col-sm-12">Error</div>
  </div>
  {% for rec in recs %}
          <form method="post" action="{% url 'callnumber_to_barcode:update' item_id=rec.item_id col_name=col_name %}?callnumber={{ request.GET.callnumber|urlencode }}">
        {% csrf_token %}
  <div class="row row {% if rec.error %}text-danger{% elif rec.new_barcode %}text-success{% endif %}">


      <div class="col-lg-2 col-md-2 col-sm-12 mb-3">
            {{ rec.callnumber }}
      </div>
      <div class="col-lg-2 col-md-2 col-sm-12 mb-3">
            {{ rec.item_id }}
      </div>
      <div class="col-lg-5 col-md-5 col-sm-12 mb-3">
            {{ rec.title }}
      </div>
      <div class="col-lg-2 col-md-2 col-sm-12 mb-3">
          <input type="text" name="new_barcode" class="form-control"
            value="{{ rec.new_barcode |default_if_none:'' }}"
            onkeydown="if(event.key === 'Enter'){ this.form.submit(); return false; }">


      </div>
      <div class="col-lg-1 col-md-1 col-sm-12 mb-3">
            {{ rec.error }}
      </div>


  </div>
      </form>

  {% empty %}
    <p><i>No result</i></p>

  {% endfor %}


  </div>
</div>
        {% else %}

<div class="alert alert-warning" role="alert">⚠️ You need to login.
</div>

{%  endif %}

    </main>
</div>
<script>csrf_token = "{{ csrf_token }}";</script>
</body>
</html>

callnumber_to_barcode/templates/callnumber_to_barcode/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>SLSP tool: callnumber => barcode</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'callnumber_to_barcode/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}">
    <script src="https://unpkg.com/vue@3.2.29/dist/vue.global.js"></script>
</head>
<body>
<div class="container-fluid">
    <header>
        <div class="row mb-2">
            <div class="col-10">
                <h1>SLSP tool: callnumber => barcode</h1>
            </div>
            <div class="col-2 text-end">
                {% if user.is_authenticated %}
                <a href="{% url 'callnumber_to_barcode:logout_view' %}">Logout</a>
                {% else %}
                <a href="{% url 'callnumber_to_barcode:login_view' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
    {% if user.is_authenticated %}
<div class="container">

<form method="get" action="{% url 'callnumber_to_barcode:index' %}" class="d-flex align-items-center mb-4">
  <label for="callnumberSearch" class="form-label me-2 mb-0">Callnumber</label>
  <input type="text" class="form-control me-2" id="callnumberSearch" name="callnumber" placeholder="Search by Callnumber" value="{{ request.GET.callnumber }}" style="max-width: 200px;">
  <button type="submit" class="btn btn-primary">Search</button>
</form>


</div>
<div class="container">
  <div class="row fw-bold border-bottom pb-2 mb-2">
    <div class="col-lg-2 col-md-2 col-sm-12">Callnumber</div>
    <div class="col-lg-2 col-md-4 col-sm-12">MMS ID</div>
    <div class="col-lg-5 col-md-8 col-sm-12">Title</div>
    <div class="col-lg-2 col-md-3 col-sm-12">New barcode</div>
    <div class="col-lg-1 col-md-1 col-sm-12">Error</div>
  </div>
  {% for rec in recs %}
          <form method="post" action="{% url 'callnumber_to_barcode:update' rec.item_id %}?callnumber={{ request.GET.callnumber|urlencode }}">
        {% csrf_token %}
  <div class="row">


      <div class="col-lg-2 col-md-2 col-sm-12 mb-3">
            {{ rec.callnumber }}
      </div>
      <div class="col-lg-2 col-md-2 col-sm-12 mb-3">
            {{ rec.item_id }}
      </div>
      <div class="col-lg-5 col-md-5 col-sm-12 mb-3">
            {{ rec.title }}
      </div>
      <div class="col-lg-2 col-md-2 col-sm-12 mb-3">
          <input type="text" name="new_barcode" class="form-control"
            value="{{ rec.new_barcode |default_if_none:'' }}"
            onkeydown="if(event.key === 'Enter'){ this.form.submit(); return false; }">


      </div>
      <div class="col-lg-1 col-md-1 col-sm-12 mb-3">
            {{ rec.error }}
      </div>


  </div>
      </form>
  {% endfor %}


  </div>
</div>
        {% else %}

<div class="alert alert-warning" role="alert">⚠️ You need to login.
</div>

{%  endif %}

    </main>
</div>
<script>csrf_token = "{{ csrf_token }}";</script>
</body>
</html>