callnumber_to_barcode/urls.py
"""
URLs for the deduplication app.
"""

from django.urls import path
from . import views

app_name = "callnumber_to_barcode"

urlpatterns = [
    # Start page with list of collections to dedup, this view is not protected by login
    path("", views.index, name="index"),
    path("<slug:col_name>", views.collection, name="collection"),
    path("<slug:col_name>/update/<str:item_id>", views.update, name="update"),
    # Views to manage login and logout. The login view does not require
    # authentication to be accessed
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view")
]

dedup/urls.py
"""
URLs for the deduplication app.
"""

from django.urls import path
from . import views

app_name = "dedup"

urlpatterns = [
    # Start page with list of collections to dedup, this view is not protected by login
    path("", views.index, name="index"),

    # Collection page with list of records to dedup, main dedup view
    path("col/<slug:col_name>", views.collection, name="collection"),

    # Collection page with list of records to dedup, main dedup view
    path("col/<slug:col_name>/export", views.get_matching_records, name="get_matching_records"),

    # API used by the frontend to get the records to dedup
    path("col/<slug:col_name>/locrecids", views.get_local_record_ids, name="get_local_record_ids"),

    # API used by the frontend to get the data of the local record to dedup
    path("col/<slug:col_name>/locrec/<str:rec_id>", views.local_rec, name="local_rec"),

    # API used by the frontend to save dedup results int the training data
    path("training/add", views.add_to_training_data, name="add_to_training_data"),

    # Views to manage login and logout. The login view does not require
    # authentication to be accessed
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view")

    # path("dnbrec/<str:rec_id>", views.get_dnb_rec, name="get_dnb_rec"),
]

slsptools/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('dedup/', include('dedup.urls')),
    path('callnumber_to_barcode/', include('callnumber_to_barcode.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),

    # Views to manage login and logout. The login view does not require
    # authentication to be accessed
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view"),
    # path("api_threshold/", views.api_threshold_probe, name="api_threshold_probe"),
]

slsptools/views.py
from django.http import HttpResponse, JsonResponse, HttpRequest
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from almapiwrapper import ApiKeys
import requests
import os
from django.core.cache import cache


def index(request: HttpRequest) -> HttpResponse:
    """
    Display the list of apps

    This view is unprotected and can be accessed by anyone.
    """

    # Render the template with the list of collections
    return render(request, 'slsptools/index.html')

def login_view(request):
    """Manage login of the user

    It uses the AuthenticationForm to authenticate the user.
    If the user is authenticated, it will redirect to the index page.
    """
    # We check the method of the request, post is used to send the form
    # and get is used to display the form
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        # We collect the data from the form and check if it's valid
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            # Redirection to the index page if the user is authenticated
            if user is not None:
                login(request, user)
                return redirect('index')

    return render(request, 'slsptools/login.html', {'form': AuthenticationForm()})

def logout_view(request):
    """Logout the user and redirect to the index page"""
    logout(request)
    return redirect('index')

def get_current_api_threshold():
    """Check the current API usage and return the status."""

    # We first check if we have a cached status
    cached_status = cache.get('api_threshold_probe_status')
    cached_remaining_api_calls = cache.get('remaining_api_calls')

    if cached_status is not None and cached_remaining_api_calls is not None:
        # We have a cached status, we return it
        status = cached_status
        remaining_api_calls = cached_remaining_api_calls
    else:
        # No cached status, we perform the API call to check the remaining calls
        env = 'S' if os.getenv('django_env') == 'dev' else 'P'
        headers = {'content-type': 'application/json',
                   'accept': 'application/json',
                   'Authorization': 'apikey ' + ApiKeys().get_key('NZ', 'Conf', 'R', env)}

        r = requests.get('https://api-eu.hosted.exlibrisgroup.com/almaws/v1/conf/test', headers=headers)

        if not r.ok:
            # No response or error response from the API => error status
            status = 'critical'
            remaining_api_calls = 'unknown'
        elif 'X-Exl-Api-Remaining' in r.headers and int(r.headers["X-Exl-Api-Remaining"]) < 100000:
            # Critical threshold reached
            status = 'critical'
            remaining_api_calls = r.headers["X-Exl-Api-Remaining"]
        elif 'X-Exl-Api-Remaining' in r.headers and int(r.headers["X-Exl-Api-Remaining"]) < 500000:
            # Warning threshold reached
            status = 'warning'
            remaining_api_calls = r.headers["X-Exl-Api-Remaining"]
        else:
            # Everything is ok, thresholds are fine
            status = 'ok'
            remaining_api_calls = r.headers.get("X-Exl-Api-Remaining", 'unknown')

        # We save the status and remaining API calls in cache for 30 minutes
        cache.set('api_threshold_probe_status', status, 1800)
        cache.set('remaining_api_calls', remaining_api_calls, 1800)

    return {'status': status, 'remaining_api_calls': remaining_api_calls}

# def api_threshold_probe(request):
#     """API view to check the current API usage and return the status.

#     This view is unprotected and can be accessed by anyone.
#     It returns a JSON response with the status and remaining API calls.
#     """

#     api_threshold = get_current_api_threshold()

#     status = ['ok', 'warning', 'critical'].index(api_threshold['status'])
#     api_threshold_str = f'{status} "Alma api calls threshold" remaining_api_calls={api_threshold["remaining_api_calls"]} - State of remaining API calls in the NZ: {api_threshold["status"].upper()}'

#     return HttpResponse(api_threshold_str)

slsptools/templates/slsptools/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>SLSP dedup tool</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'dedup/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}">
    <script src="https://unpkg.com/vue@3.2.29/dist/vue.global.js"></script>
</head>
<body>
<div class="container-fluid">
    <header>
        <div class="row mb-2">
            <div class="col-10">
                <h1>SLSP dedup tool</h1>
            </div>
            <div class="col-2 text-end">
                {% if user.is_authenticated %}
                <a href="{% url 'logout_view' %}">Logout</a>
                {% else %}
                <a href="{% url 'login_view' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    Available collections:
                </div>
            </div>
            <div class="row">
                <ul class="col-lg-4 col-sm-12 list-group">
                    <li class="list-group-item"><a href="{% url 'dedup:index' %}" class="text-break">SLSP dedup tool</a></li>
                    <li class="list-group-item"><a href="{% url 'callnumber_to_barcode:index' %}" class="text-break">SLSP callnumber to barcode tool</a></li>
                </ul>
            </div>
        </div>
    </main>
</div>
<script>csrf_token = "{{ csrf_token }}";</script>
</body>
</html>

slsptools/templates/slsptools/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>SLSP dedup tool: login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center">SLSP tools</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center">Login</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Login</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>